// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiUrl": string;
      "apiKey": string;
      "model": string;
      "maxHistoryRounds": number;
      "enableToolCalling": boolean;
      "systemPrompt": string;
    };
  }
}
